version: '3'

services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/stateCompany
    ports:
      - '8000:8000'
    depends_on:
      - db